#Full Model
# model_path: /student/tahmad8/Videos/tofu/model/target_model/full_model_scratch/

# Retain Model
model_path: /student/tahmad8/Videos/tofu/model/target_model/ft_epoch5_lr1e-05_llama2-7b_retain90_wd0.01

# Forget Model
#model_path: /student/tahmad8/Videos/tofu/model/forget_model/mixed_distillation_v2/
model_family: llama2-7b

save_dir: ${model_path}/eval_results/
#save_dir: /student/tahmad8/Videos/tofu/model/target_model/eval_results/
#dataset path for each of the 4 datasets to be evaluated
data_path: [locuslab/TOFU, locuslab/TOFU] 
split: forget10_perturbed
split_list:
  - retain_perturbed
  - ${split}


question_key: [question, question]
answer_key: [answer, answer]

base_answer_key: [answer, answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_log_forget]

generation:
  max_length: 500
  max_new_tokens: null

save_generated_text: true

ds_size: 4000

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false

retain_result: null

